# Generated by Django 3.2 on 2021-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0002_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='produced_by',
            field=models.TextField(blank=True),
        ),
    ]
