# Generated by Django 3.2 on 2021-04-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0003_auto_20210412_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_weight',
        ),
    ]
