# Generated by Django 3.2 on 2021-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0004_remove_product_standard_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_weight',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
