# Generated by Django 3.2 on 2021-04-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0005_product_standard_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_weight',
        ),
    ]
