# Generated by Django 3.2 on 2021-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0006_remove_product_standard_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories_per100',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates_per100',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_per100',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fibre_per100',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_per100',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_per100',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='fibre',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
