# Generated by Django 3.2 on 2021-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0007_auto_20210412_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='produced_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
