# Generated by Django 3.2 on 2021-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0008_alter_product_produced_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='E:\\Zajęcia\\djangoProject1\\FoodCalories\\media'),
        ),
    ]
