# Generated by Django 3.2 on 2021-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='/static/img/default.png', upload_to='E:\\Zajęcia\\djangoProject1\\FoodCalories\\media'),
        ),
    ]
