# Generated by Django 3.2 on 2021-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodLibrary', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
